GRID_SIZE = 100

INITIAL_PYTHONS = 300

MOVE_RANGE = 1

BASE_REPRODUCTION_RATE = 0.04
DEATH_RATE = 0.01

SIMULATION_STEPS = 300

MAX_LOCAL_DENSITY = 8

# CONTROL SYSTEMS
NUM_HUNTERS = 8

BASE_DETECTION_PROBABILITY = 0.35

REMOVAL_SUCCESS_RATE = 0.75